parameters:
- name: env  # defaults for any parameters that aren't specified
  default: 'UAT'
- name: pool
  default: 'None'
    
jobs:
  - deployment:  
    environment: ${{ parameters.env }}
  
    pool:
      vmImage: ${{ parameters.pool }}

    strategy:
        runOnce:
            deploy:
              steps:
              - bash: echo "Hello ${{ parameters.env }}"