parameters:
- name: Env  # defaults for any parameters that aren't specified
  default: 'UAT'
- vmImage: pool
  default: 'None'
    
jobs:
  - deployment:  
    environment: ${{ parameters.Env }}
  
    pool:
      vmImage: ${{ parameters.pool }}

    strategy:
        runOnce:
            deploy:
              steps:
              - bash: echo "Hello ${{ parameters.Env }}"